### ISSUE TITLE
:SWServerStart command not working

### ISSUE THREAD

**Issue by cosminadrianpopescu** [cosminadrianpopescu/vim-sql-workbench#8]
Reported in the incident #1

**Comment by sluedtke** [comment]
Starting the server from (g)vim does not work.

```
:SWServerStart 5000
:SWSqlConnectToServer 5000 /tmp/test.sql
:SWSqlExecuteCurrent
```

The last one does not work and gives the following error:

```
Processing a command. Please wait...
Error detected while processing function sw#sqlwindow#execute_sql..sw#execute_sql..sw#server#execute
_sql..<SNR>132_pipe_execute:
line   54:
Traceback (most recent call last):
  File "<string>", line 9, in <module>
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
line   55:
E121: Undefined variable: result
E116: Invalid arguments for function len(result) <= 3
E15: Invalid expression: len(result) <= 3
line   58:
E121: Undefined variable: result
E116: Invalid arguments for function substitute(result, '\r', '', 'g')
E15: Invalid expression: substitute(result, '\r', '', 'g')      
```

The command from the sql buffer I try to execute is:

`wbconnect crop_db;`

**Comment by cosminadrianpopescu** [comment]
WIth the version 6.0, there is no need for any server, so I will close the ticket
